force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FL-{00000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TKT-{00000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Flight Lookup relationship - references Flight__c object</description>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP-{00000}</displayFormat>
        <label>Trip Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <description>Show only flights that match preferred start date and have available tickets</description>
        <filterItems>
            <field>Flight__c.Start__c</field>
            <operation>equals</operation>
            <valueField>$Source.Preferred_Trip_Start__c</valueField>
        </filterItems>
        <filterItems>
            <field>Flight__c.Available_Tickets__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <infoMessage>Only flights matching your preferred start date with available tickets are shown.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Application.cls
public class Application {
    
    public static final fflib_Application.UnitOfWorkFactory UnitOfWork = 
        new fflib_Application.UnitOfWorkFactory(
            new List<SObjectType> {
                Trip__c.SObjectType,
                Flight__c.SObjectType, 
                Ticket__c.SObjectType
            }
        );
        
    public static final fflib_Application.SelectorFactory Selector = 
        new fflib_Application.SelectorFactory(
            new Map<SObjectType, Type> {
                Trip__c.SObjectType => TripsSelector.class,
                Flight__c.SObjectType => FlightsSelector.class,
                Ticket__c.SObjectType => TicketsSelector.class,
                Contact.SObjectType => ContactsSelector.class
            }
        );
        
    public static final fflib_Application.DomainFactory Domain = 
        new fflib_Application.DomainFactory(
            Application.Selector,
            new Map<SObjectType, Type> {
                Trip__c.SObjectType => TripsDomain.class,
                Flight__c.SObjectType => FlightsDomain.class,
                Ticket__c.SObjectType => TicketsDomain.class
            }
        );

}